// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmegtvjshpkpcjirsbnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZWd0dmpzaHBrcGNqaXJzYm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NjkzNzEsImV4cCI6MjA1ODI0NTM3MX0.VWURnJEKD5JA1wVM1g_9WXydY-W7W1YvsYAxZKL21G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);