
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhizloiugyuqcxgaoiff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oaXpsb2l1Z3l1cWN4Z2FvaWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDM4MjcsImV4cCI6MjA1ODM3OTgyN30.O8Tf2zhetC8-htKA0fSWllHGhYmYXIIQ2_9Mzpq7cGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
